---
- name: Check Linux Version
  hosts: server
  gather_facts: true
  tasks:
    - name: Get Ubuntu version
      command: "lsb_release -a"
      register: ubuntu_version_output
      when: "'Ubuntu' in ansible_distribution"

    - name: Get CentOS version
      command: "rpm -q centos-release"
      register: centos_version_output
      when: "'CentOS' in ansible_distribution"

    - name: Display Linux version
      debug:
        msg: "Linux version on {{ inventory_hostname }} is {{ ubuntu_version_output.stdout_lines[1] if 'Ubuntu' in ansible_distribution else centos_version_output.stdout_lines[0] }}"