---
- name: Check Zabbix_agent Version
  hosts: server
  gather_facts: true
  tasks:
    - name: Get Zabbix_agent Version
      command: "zabbix_agent2 -V"
      register: zabbix_version_output

    - name: Display Zabbix_agent version
      debug:
        var: zabbix_version_output.stdout_lines

        #msg: "Zabbix Agent version on {{ inventory_hostname }} is {{ zabbix_version_output.stdout_lines[0] }}"
        #msg: "Zabbix Agent version on {{ inventory-man }} is {{ zabbix_version_output.stdout_lines[0] }}"

        #testsss