--- 
- hosts: THBDAUTH301
  gather_facts: yes
  #remote_user: root
  become: yes
  
  tasks:
    # This task updates our CentOS based systems
    - name: .rpm upgrade server
      yum: >
        update_cache=yes
        name=*
        state=none
        update_cache=yes
      when: >
        ansible_distribution == 'CentOS'
 
    # This task updates our Ubuntu based systems
    - name: .deb do dist-upgrade
      apt: >
        update_cache=yes
        cache_valid_time=1200
        upgrade=no
      when: >
        ansible_distribution == 'Ubuntu'
        #sdasdss
