---

- hosts: hq_switch

  gather_facts: no

  connection: local

 

  vars_prompt:

  - name: "mgmt_username"

    prompt: "Username"

    private: no

  - name: "mgmt_password"

    prompt: "Password"



  tasks:



  - name: SYS | Define provider

    set_fact:

      provider:

        host: "{{ inventory_hostname }}" 

        username: "{{ mgmt_username }}"

        password: "{{ mgmt_password }}"


  - name: Config FTP

    ios_config:

      provider: "{{ provider }}"

      lines:
        
        - ip ftp username administrator

        - ip ftp password gl2004

  
  - name: IOS | Save Config

    ios_command:

      provider: "{{ provider }}"

      commands:

        - write-memory
