---

- hosts: ios_devices

  gather_facts: no

  connection: local

 

  vars_prompt:

  - name: "mgmt_username"

    prompt: "Username"

    private: no

  - name: "mgmt_password"

    prompt: "Password"
 
  vars:

    backup_root: /tmp/backups


  tasks:



  - name: SYS | Define provider

    set_fact:

      provider:

        host: "{{ inventory_hostname }}" 

        username: "{{ mgmt_username }}"

        password: "{{ mgmt_password }}"



  - name: IOS | Show runing
    ios_command:
      provider: "{{ provider }}"
      commands:
        - show run
    register: config

  - name: ensure backup folder is created

    file:

      path: "{{ backup_root }}"

      state: directory

    run_once: yes

 
  - name: ensure device rolder is created

    file:

        path: "{{ backup_root }}/{{ inventory_hostname }}"

        state: directory
  - name: get timestamp

    command: date +%Y%m%d

    register: timestamp



  - copy:

      content: "{{ config.stdout[0] }}"

      dest: "{{ backup_root }}/{{ inventory_hostname }}/running-config_{{ timestamp.stdout }}"


