---

- hosts: ios_devices

  gather_facts: no

  connection: local

 

  vars_prompt:

  - name: "mgmt_username"

    prompt: "Username"

    private: no

  - name: "mgmt_password"

    prompt: "Password"



  tasks:



  - name: SYS | Define provider

    set_fact:

      provider:

        host: "{{ inventory_hostname }}" 

        username: "{{ mgmt_username }}"

        password: "{{ mgmt_password }}"


  - name: IOS | Show Run Interface 

    ios_command:

      provider: "{{ provider }}"

      commands:

        - show run interface GigabitEthernet1/0/27

    register: run


  - debug: msg="{{ run.stdout_lines }}"
