---
- hosts: all
  gather_facts: yes
  #remote_user: root
  become: yes
  tasks:
    - name: insert new rule after 
      pamd:
        name: common-password
        type: auth
        control: required
        module_path: pam_env.so
        new_type: auth
        new_control: required
        new_module_path: pam_faillock.so
        state: after
    - name: Update Accout fail and account release unlock_time=3600
      pamd:
        name: common-password
        type: auth
        control: required
        module_path: pam_faillock.so
        module_arguments: "preauth 
            silent 
            audit 
            deny=5 
            unlock_time=3600"
        state: updated
    - name: set old password remember 5
      pamd:
        name: common-password
        type: password
        control: sufficient
        module_path: pam_unix.so
        module_arguments: "sha512 shadow nullok try_first_pass use_authtok remember=5"
        state: updated
    - name: Set Password Expiration MAX Days
      lineinfile:
        dest: '/etc/login.defs'
        regexp: "PASS_MAX_DAYS"
        line: "PASS_MAX_DAYS 90"
        state: present

    - name: Set Password Expiration MIN Days
      lineinfile:
        dest: '/etc/login.defs'
        regexp: "PASS_MIN_DAYS"
        line: "PASS_MIN_DAYS 7"
        state: present
    - name: Set Password  MIN Lengh
      lineinfile:
        dest: '/etc/login.defs'
        regexp: "PASS_MIN_LEN"
        line: "PASS_MIN_LEN 8"
        state: present
    - name: Set Password Expiration Warn Days
      lineinfile:
        dest: '/etc/login.defs'
        regexp: "PASS_WARN_AGE"
        line: "PASS_WARN_AGE 14"
        state: present
    - name: Set Session Idle Timeout
      lineinfile:
        dest: '/etc/ssh/sshd_config'
        regexp: "#ClientAliveInterval 0"
        line: "ClientAliveInterval 15m"
        state: present
