---
- hosts: all
  gather_facts: yes
  strategy: free
  #remote_user: root
  become: yes

  tasks:
    - name: Restart service filebeat, in all cases
      service:
        name: metricbeat
        state: stopped
